Simulación N Partículas: Bola Class Reference
Bola Class Reference
Representa una partícula esférica con posición, velocidad y propiedades físicas.
#include <Bola.h>
Public Member Functions
Bola ()
Bola (double x, double y, double vx, double vy, double masa, double radio)
void Iniciar (double x, double y, double vx, double vy, double masa, double radio)
void MoverseEuler (double dt)
void MoverseVerlet (double dt, double ax=0.0, double ay=0.0)
void RebotePared (double W, double H)
bool HayColision (const Bola &otra) const
void Choque (Bola &otra)
double EnergiaCinetica () const
double Rapidez () const
double GetX () const
double GetY () const
double GetVx () const
double GetVy () const
double GetMasa () const
double GetRadio () const
void SetVx (double vx)
void SetVy (double vy)
Detailed Description
Representa una partícula esférica con posición, velocidad y propiedades físicas.
Definition at line 18 of file Bola.h.
Constructor & Destructor Documentation
Bola() [1/2]
Bola::Bola ()
Definition at line 8 of file Bola.cpp.
Bola() [2/2]
Bola::Bola (double x, double y, double vx, double vy, double masa, double radio)
Definition at line 10 of file Bola.cpp.
Member Function Documentation
Choque()
void Bola::Choque (Bola & otra)
Definition at line 61 of file Bola.cpp.
References HayColision().
EnergiaCinetica()
double Bola::EnergiaCinetica () const
Definition at line 98 of file Bola.cpp.
GetMasa()
double Bola::GetMasa () const inline
Definition at line 44 of file Bola.h.
GetRadio()
double Bola::GetRadio () const inline
Definition at line 45 of file Bola.h.
GetVx()
double Bola::GetVx () const inline
Definition at line 42 of file Bola.h.
GetVy()
double Bola::GetVy () const inline
Definition at line 43 of file Bola.h.
GetX()
double Bola::GetX () const inline
Definition at line 40 of file Bola.h.
GetY()
double Bola::GetY () const inline
Definition at line 41 of file Bola.h.
HayColision()
bool Bola::HayColision (const Bola & otra) const
Definition at line 53 of file Bola.cpp.
Referenced by Choque(), and Caja::InicializarAleatorio().
Iniciar()
void Bola::Iniciar (double x, double y, double vx, double vy, double masa, double radio)
Definition at line 13 of file Bola.cpp.
MoverseEuler()
void Bola::MoverseEuler (double dt)
Definition at line 22 of file Bola.cpp.
MoverseVerlet()
void Bola::MoverseVerlet (double dt, double ax = 0.0, double ay = 0.0)
Definition at line 27 of file Bola.cpp.
Rapidez()
double Bola::Rapidez () const
Definition at line 102 of file Bola.cpp.
RebotePared()
void Bola::RebotePared (double W, double H)
Definition at line 34 of file Bola.cpp.
SetVx()
void Bola::SetVx (double vx) inline
Definition at line 48 of file Bola.h.
SetVy()
void Bola::SetVy (double vy) inline
Definition at line 49 of file Bola.h.
The documentation for this class was generated from the following files:
include/Bola.h
src/Bola.cpp