Simulación N Partículas: Caja Class Reference
Caja Class Reference
Gestiona un sistema de N partículas en una caja rectangular.
#include <Caja.h>
Public Member Functions
Caja (double ancho, double alto)
void InicializarRejilla (int N, double masa, double radio, double v_max)
void InicializarAleatorio (int N, double masa, double radio, double v_max)
void EvolucionarEuler (double dt)
void EvolucionarVerlet (double dt)
void DetectarColisiones ()
double EnergiaTotal () const
void GuardarEstado (std::ofstream &archivo, double tiempo) const
void SimularCompleto (double t_final, double dt, double dt_salida, const std::string &nombre_archivo, bool usar_verlet=true)
int GetNumChoquesPared () const
int GetNumBolas () const
void ResetearChoques ()
Detailed Description
Gestiona un sistema de N partículas en una caja rectangular.
Definition at line 21 of file Caja.h.
Constructor & Destructor Documentation
Caja()
Caja::Caja (double ancho, double alto)
Definition at line 10 of file Caja.cpp.
Member Function Documentation
DetectarColisiones()
void Caja::DetectarColisiones ()
Definition at line 133 of file Caja.cpp.
Referenced by EvolucionarEuler(), and EvolucionarVerlet().
EnergiaTotal()
double Caja::EnergiaTotal () const
Definition at line 144 of file Caja.cpp.
Referenced by Experimento1GasDiluido(), Experimento2GasDenso(), Experimento3ComparacionMetodos(), and SimularCompleto().
EvolucionarEuler()
void Caja::EvolucionarEuler (double dt)
Definition at line 85 of file Caja.cpp.
References DetectarColisiones().
Referenced by SimularCompleto().
EvolucionarVerlet()
void Caja::EvolucionarVerlet (double dt)
Definition at line 109 of file Caja.cpp.
References DetectarColisiones().
Referenced by SimularCompleto().
GetNumBolas()
int Caja::GetNumBolas () const inline
Definition at line 41 of file Caja.h.
GetNumChoquesPared()
int Caja::GetNumChoquesPared () const inline
Definition at line 40 of file Caja.h.
Referenced by Experimento4Presion().
GuardarEstado()
void Caja::GuardarEstado (std::ofstream & archivo, double tiempo) const
Definition at line 152 of file Caja.cpp.
Referenced by SimularCompleto().
InicializarAleatorio()
void Caja::InicializarAleatorio (int N, double masa, double radio, double v_max)
Definition at line 43 of file Caja.cpp.
References Bola::HayColision().
InicializarRejilla()
void Caja::InicializarRejilla (int N, double masa, double radio, double v_max)
Definition at line 16 of file Caja.cpp.
Referenced by Experimento1GasDiluido(), Experimento2GasDenso(), Experimento3ComparacionMetodos(), Experimento4Presion(), and Experimento5Velocidades().
ResetearChoques()
void Caja::ResetearChoques () inline
Definition at line 42 of file Caja.h.
SimularCompleto()
void Caja::SimularCompleto (double t_final, double dt, double dt_salida, const std::string & nombre_archivo, bool usar_verlet = true)
Definition at line 161 of file Caja.cpp.
References EnergiaTotal(), EvolucionarEuler(), EvolucionarVerlet(), and GuardarEstado().
Referenced by Experimento1GasDiluido(), Experimento2GasDenso(), Experimento3ComparacionMetodos(), Experimento4Presion(), and Experimento5Velocidades().
The documentation for this class was generated from the following files:
include/Caja.h
src/Caja.cpp